### ISSUE TITLE
Create custom kudu deployment script for website

### ISSUE THREAD

**Issue by nzthiago** [MicrosoftDX/liquidintel#30]
Needs to run 'npm deploy build' after 'npm install'. If only the default kudu 'npm install' runs the website is not fully built.

**Comment by brusMX** [comment]
Actually it needs to run `npm i` and ` npm run build:prod`

**Comment by nzthiago** [comment]
This was implemented in this PR https://github.com/MicrosoftDX/liquidintel/pull/39
