### ISSUE TITLE
Request: Shopping list of hardware items to replicate

### ISSUE THREAD

**Issue by tomorgan** [MicrosoftDX/liquidintel#44]
Hi guys,

Thanks for making this project open and on GitHub. What would be really useful would be if you could list out the hardware bits you used to put all this together. For someone wanting to replicate the process and take your code as a starting point, understanding how you are using it and what hardware you're working with would be really handy. I'm thinking maybe a page/blog post with all the parts, photos of them, what they're for, where they came from, what they cost?  I appreciate it's a bit of a PITA to do, but info like that is really handy for people like me coming into this and wondering if we can do the same thing.  Thanks!!

**Comment by nzthiago** [comment]
Hi @tomorgan, great request. I added [a new file](https://github.com/MicrosoftDX/liquidintel/blob/master/bom.md) to our repo with the list of hardware we used.

**Comment by tomorgan** [comment]
brill thanks :)
